// IMPORTANT!
// This file has been automatically generated,
// in order to update its content execute "npm run update"
export const ruleNames = [
  "array-bracket-newline",
  "array-bracket-spacing",
  "array-element-newline",
  "auto",
  "comma-dangle",
  "comma-style",
  "indent",
  "key-name-casing",
  "key-spacing",
  "no-bigint-literals",
  "no-binary-expression",
  "no-binary-numeric-literals",
  "no-comments",
  "no-dupe-keys",
  "no-escape-sequence-in-identifier",
  "no-floating-decimal",
  "no-hexadecimal-numeric-literals",
  "no-infinity",
  "no-irregular-whitespace",
  "no-multi-str",
  "no-nan",
  "no-number-props",
  "no-numeric-separators",
  "no-octal-escape",
  "no-octal-numeric-literals",
  "no-octal",
  "no-parenthesized",
  "no-plus-sign",
  "no-regexp-literals",
  "no-sparse-arrays",
  "no-template-literals",
  "no-undefined-value",
  "no-unicode-codepoint-escapes",
  "no-useless-escape",
  "object-curly-newline",
  "object-curly-spacing",
  "object-property-newline",
  "quote-props",
  "quotes",
  "sort-array-values",
  "sort-keys",
  "space-unary-ops",
  "valid-json-number",
  "vue-custom-block/no-parsing-error",
] as const;
